@startuml Main
title: <size:20><&heart>广告系统<&heart></size>
class Advertisement[ww_ad] {
    ad_id
    ad_sn
    position_id
    ad_name
    game_id
    settlement
    ad_url_id
    ad_site_id
    has_landing_page
    ad_url_id
    style_id
    style_type
    admin_id
    is_hide
    media_id
    agent_id
    promote_id
    sub_promote_id
    template_id
    material_info
    add_time
    edit_time
    down_id
    create_time
}

note left
    "可访问性"
    "-  private"
    "#  protected"
    "~ package private"
    "+  public"
end note
@enduml